# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Desktop/LinkedList

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Desktop/LinkedList

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Desktop/LinkedList/CMakeFiles /home/student/Desktop/LinkedList/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Desktop/LinkedList/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linkedtest

# Build rule for target.
linkedtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linkedtest
.PHONY : linkedtest

# fast build rule for target.
linkedtest/fast:
	$(MAKE) -f CMakeFiles/linkedtest.dir/build.make CMakeFiles/linkedtest.dir/build
.PHONY : linkedtest/fast

#=============================================================================
# Target rules for targets named linkedperf

# Build rule for target.
linkedperf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linkedperf
.PHONY : linkedperf

# fast build rule for target.
linkedperf/fast:
	$(MAKE) -f CMakeFiles/linkedperf.dir/build.make CMakeFiles/linkedperf.dir/build
.PHONY : linkedperf/fast

linked_perf.o: linked_perf.cpp.o

.PHONY : linked_perf.o

# target to build an object file
linked_perf.cpp.o:
	$(MAKE) -f CMakeFiles/linkedperf.dir/build.make CMakeFiles/linkedperf.dir/linked_perf.cpp.o
.PHONY : linked_perf.cpp.o

linked_perf.i: linked_perf.cpp.i

.PHONY : linked_perf.i

# target to preprocess a source file
linked_perf.cpp.i:
	$(MAKE) -f CMakeFiles/linkedperf.dir/build.make CMakeFiles/linkedperf.dir/linked_perf.cpp.i
.PHONY : linked_perf.cpp.i

linked_perf.s: linked_perf.cpp.s

.PHONY : linked_perf.s

# target to generate assembly for a file
linked_perf.cpp.s:
	$(MAKE) -f CMakeFiles/linkedperf.dir/build.make CMakeFiles/linkedperf.dir/linked_perf.cpp.s
.PHONY : linked_perf.cpp.s

linked_test.o: linked_test.cpp.o

.PHONY : linked_test.o

# target to build an object file
linked_test.cpp.o:
	$(MAKE) -f CMakeFiles/linkedtest.dir/build.make CMakeFiles/linkedtest.dir/linked_test.cpp.o
.PHONY : linked_test.cpp.o

linked_test.i: linked_test.cpp.i

.PHONY : linked_test.i

# target to preprocess a source file
linked_test.cpp.i:
	$(MAKE) -f CMakeFiles/linkedtest.dir/build.make CMakeFiles/linkedtest.dir/linked_test.cpp.i
.PHONY : linked_test.cpp.i

linked_test.s: linked_test.cpp.s

.PHONY : linked_test.s

# target to generate assembly for a file
linked_test.cpp.s:
	$(MAKE) -f CMakeFiles/linkedtest.dir/build.make CMakeFiles/linkedtest.dir/linked_test.cpp.s
.PHONY : linked_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... linkedtest"
	@echo "... linkedperf"
	@echo "... linked_perf.o"
	@echo "... linked_perf.i"
	@echo "... linked_perf.s"
	@echo "... linked_test.o"
	@echo "... linked_test.i"
	@echo "... linked_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

